spring.application.name=SpringSecurityRoleBased-1

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/springsecurityauth
spring.datasource.username=root
spring.datasource.password=sowmya@03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect