spring.application.name=SpringSecurity

server.port = 9090

spring.security.user.name=admin
spring.security.user.password=admin@123

#default username is -> user
#password is generated in teh console 